### ISSUE TITLE
Firmware make all für Controllerboard make scheitert

### ISSUE THREAD

**Issue by AndreasW79** [hcanIngo/openHCAN#14]
Hallo zusammen,

auf meinem aktuellen Testsystem (raspbian 9) läuft soweit alles, allerdings wirft das kompilieren der Firmwares des Controllerboards einen Fehler:

Ich gehe davon aus, dass irgendetwas nicht optimal passt oder fehlt:

```
timer.c:(.text+0x332): undefined reference to `ports_timer_handler'
timer.c:(.text+0x33a): undefined reference to `tempsensor_timer_handler'
timer.c:(.text+0x342): undefined reference to `rolladenSchlitzpos_timer_handler'
timer.c:(.text+0x34a): undefined reference to `poti_timer_handler'
timer.c:(.text+0x352): undefined reference to `rolladen_timer_handler'
timer.c:(.text+0x35a): undefined reference to `powerport_timer_handler'
timer.c:(.text+0x362): undefined reference to `schalter_timer_handler'
/tmp/cc2kLdIL.o: In function `darlingtonoutput_getpin':
darlingtonoutput.c:(.text+0x4e): undefined reference to `ports_getOutput'
/tmp/cc2kLdIL.o: In function `darlingtonoutput_setpin':
darlingtonoutput.c:(.text+0xb6): undefined reference to `ports_setOutput'
collect2: error: ld returned 1 exit status
Makefile:47: die Regel für Ziel "main.elf" scheiterte
make[1]: *** [main.elf] Fehler 1
make[1]: Verzeichnis "/opt/openHCAN/firmwares/controllerboard" wird verlassen
Makefile:35: die Regel für Ziel "all" scheiterte
make: *** [all] Fehler 2
```

Folgende Versionen sind in der Toolchain installiert, ggf. ist hier auch eine Version nicht kompatibel:

```
clang ist schon die neueste Version (1:3.8-36).
g++ ist schon die neueste Version (4:6.3.0-4).
indent ist schon die neueste Version (2.2.11-5).
libboost-dev ist schon die neueste Version (1.62.0.1+b4).
libboost-program-options-dev ist schon die neueste Version (1.62.0.1+b4).
libboost-regex-dev ist schon die neueste Version (1.62.0.1+b4).
libreadline-gplv2-dev ist schon die neueste Version (5.2+dfsg-3).
libxml++2.6-dev ist schon die neueste Version (2.40.1-1).
pkg-config ist schon die neueste Version (0.29-4).
sshpass ist schon die neueste Version (1.06-1).
xalan ist schon die neueste Version (1.11-6).
avarice ist schon die neueste Version (2.13+svn347-4).
gdb-avr ist schon die neueste Version (7.7-4).
avr-libc ist schon die neueste Version (1:2.0.0+Atmel3.6.1-1~rpt1).
avrdude ist schon die neueste Version (6.3+r1425-1+rpt1).
gcc-avr ist schon die neueste Version (1:5.4.0+Atmel3.6.1-1~rpt1).
```
Was mir auch noch aufgefallen ist und erst durch eine Änderung im Makefile behoben werden konnte sind die errors die durch den Kompiler geworfen werden, z. B.

`In file included from ./devices/../../controllerboard/devices.h:18:0,
                 from ./devices/zeitschaltuhr.c:20:
./devices/../../controllerboard/devices/analogComparator.h:36:13: error: inline function "analogComparator_timer_handler" declared but never defined [-Werror]
 inline void analogComparator_timer_handler(device_data_analogComparator *p, uint8_t zyklus);
`
Beheben konnte ich das nur durch das Hinzufügen von 
`-Wno-error` im Makefile nach `-Werror` (vermutlich würde auch das entfernen von -Werror schon helfen...)

Vielleicht habt ihr ja eine Idee warum die Firmware für das Controllerboard nicht erstellt werden können. Für das USV Modul und das Userpanel funktioniert es problemlos

Grüße
_Andreas

**Comment by RealMerlin** [comment]
Hallo Andreas,
also ich hab mir mal den aktuellen Stand geladen und durch kompiliert, geht
problemlos. Aber du hast (nehme ich mal an) einen eigene bzw. alten Stand?
Dann hab ich mal versucht deinen Fehler nachzustellen.

Und zwar, wenn ich z.B. in der tempsensor.c die tempsensor_timer_handler
Funktion umbenenne (z.B. tempsensor_timer_handler1)
Und in der tempsensor.h noch der korrekte Name steht, bekomme ich genau
deinen Fehler:
> /tmp/ccQxi8lW.o: In Funktion `idle_handler':
> timer.c:(.text+0xf8): Nicht definierter Verweis auf
`tempsensor_timer_handler'
> timer.c:(.text+0x1d6): Nicht definierter Verweis auf
`tempsensor_timer_handler'
> timer.c:(.text+0x332): Nicht definierter Verweis auf
`tempsensor_timer_handler'
> collect2: error: ld returned 1 exit status
> Makefile:47: die Regel für Ziel „main.elf“ scheiterte


Am 17. Juli 2018 um 13:03 schrieb Andreas W <notifications@github.com>:

**Comment by AndreasW79** [comment]
Hallo @RealMerlin ,

dieses Detail habe ich natürlich unterschlagen, es war ein aktueller clone aus github von Montag.
Somit sollte es eigentlich die aktuelle Version gewesen sein.
Nutzt Du auch eine rpi mit dem aktuellen raspbian?

Grüße

**Comment by RealMerlin** [comment]
Hallo Andreas,
ich hatte es gestern auf meinem ubuntu Rechner kompiliert.
Ich hatte jetzt nur einen raspi mit wheezy da, also nicht die aktuellste
Version.
Da kompiliert es aber auch.

Ich setzte heute abend einen raspi mit der aktuellste Version auf und teste
es noch mal.


--
Gruß Martin


Andreas W <notifications@github.com> schrieb am Mi., 18. Juli 2018, 21:41:

**Comment by AndreasW79** [comment]
Hallo Merlin,

vielen Dank dafür.
Was mich aber noch wundert ist sind die Meldungen des Compilers, entweder ist der in stretch verwendete sehr empfindlich oder diese Fehler müssten bei jedem auflaufen 

`In file included from ./devices/../../controllerboard/devices.h:14:0,
                 from ./devices/zeitschaltuhr.c:20:
./devices/../../controllerboard/devices/multitaster.h:44:13: error: inline function âmultitaster_timer_handlerâ declared but never defined [-Werror]
 inline void multitaster_timer_handler(device_data_multitaster *p, uint8_t zyklus);
             ^
In file included from ./devices/../../controllerboard/devices.h:12:0,
                 from ./devices/zeitschaltuhr.c:20:
./devices/../../controllerboard/devices/reedkontakt.h:24:13: error: inline function âreedkontakt_timer_handlerâ declared but never defined [-Werror]
 inline void reedkontakt_timer_handler(device_data_reedkontakt *p, uint8_t zyklus);
             ^
In file included from ./devices/../../controllerboard/devices.h:10:0,
                 from ./devices/zeitschaltuhr.c:20:
./devices/../../controllerboard/devices/zentralheizungspumpe.h:57:13: error: inline function âzentralheizungspumpe_timer_handlerâ declared but never defined [-Werror]
 inline void zentralheizungspumpe_timer_handler(device_data_zentralheizungspumpe *p, uint8_t zyklus);
             ^
cc1: all warnings being treated as errors
./devices/helligkeitssensor.c:69:42: error: âgetADCvalue_invertedâ is static but used in inline function âhelligkeitssensor_timer_handlerâ which is not static [-Werror]
    addToFloatAvg(&(p->filterBrightness), getADCvalue_inverted());
                                          ^
./devices/helligkeitssensor.c:68:4: error: âsetADMUXâ is static but used in inline function âhelligkeitssensor_timer_handlerâ which is not static [-Werror]
    setADMUX(p->config.port);
    ^
cc1: all warnings being treated as errors
`
Das kann ich wie gesagt nur verhindern, in dem man Wno-error den cflags hinzfügt, vermutlich auch wenn man Werror entfernen würde.

Ich habe gerade das image nochmal komplett neu geschrieben und mich exakt an die Vorgaben für Ubuntu gehalten, mit dem gleichen Effekt.
Welche Compiler Version wird denn empfohlen?

Grüße
Andreas

**Comment by hcanIngo** [comment]
Hallo Andreas,
habe das openHCAN-master.zip von hier heruntergeladen, entpackt und dann in openHCAN-master ein make durchgeführt. Läuft. Anleitung findest du hier: https://github.com/hcanIngo/openHCAN/wiki/entwicklungsumgebung_installieren

Den zuletzt von mir verwendeten Compiler findest du hier: https://github.com/hcanIngo/openHCAN/blob/master/liesmich.txt

Wenn wir den Compilerschalter -Werror weglassen, dann werden sich im Laufe der Zeit immer mehr "warnings" einschleichen. Daher wäre das keine gute Idee.

Grüße,
Ingo

**Comment by AndreasW79** [comment]
... ein paar Stunden später ...
Mit dem Parameter -fgnu89-inline funktioniert es.

Die Erklärung hierzu findet man hier:
[https://gcc.gnu.org/gcc-5/porting_to.html](https://gcc.gnu.org/gcc-5/porting_to.html)

Danke für die Hilfe.

Grüße
Andreas

**Comment by hcanIngo** [comment]
Hallo Andreas,
geht doch :) 
Aber im Ernst: Dafür ist die getestete Compilerversion notiert. Und keiner von uns kann alles testen. Scheitert schon daran, das z. B. ich den Bananapi mit Armbian 5.34 (Debian 9 - Stretch) verwende: https://github.com/hcanIngo/openHCAN/wiki/bananapi-hi

### Zusammenfassung: Bei folgenden Compilerversionen:  
- avr-libc 2.0.0
- avr-gcc (GCC) 5.4.0
- cmake 3.7.2-1
- gcc (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516
- clang version 4.0.1-10+rpi1~bpo9+1 (tags/RELEASE_401/final)

### ist erst einmal folgender Compilerschalter nötig:
-fgnu89-inline

**Comment by AndreasW79** [comment]
Hallo Ingo,

Deine Anmerkung zu dem Hinweis auf die notierte Compilerversion verstehe ich nur anteilig, denn ich verwende ja genau die Compiler Version - zumindest die gcc Version welche [hier](https://github.com/hcanIngo/openHCAN/blob/master/liesmich.txt) notiert ist und in dem Hinweis zur Version fehlt m. E. der Hinweis auf -fgnu89-inline - oder habe ich das irgendwo übersehen?

Ich werde heute noch einmal ein neues Image vorbereiten und mit den Stretch (das aktuelle Rasbpian basiert auch auf Debian 9 - Stretch) Versionen einen Build testen. Wenn es nur der Parameter -fgnu89-inline ist wäre die Ergänzung in dem Hinweis, zumindest im Kontext zum Raspberry, hilfreich :)

Ich würde auch anbieten den Pages/Wiki Bereich um eine Seite zum Raspberry zu ergänzen. 

Grüße
Andreas

**Comment by RealMerlin** [comment]
Hallo zusammen,
ich konnte es erst heute nachstellen.
Aber es passiert bei meinen raspi das selbe.

Ich hab über den link von Andreas und div. Foren Beiträge rausgefunden,
dass die Deklaration in der h file mit extern (ohne inline) erfolgen sollte
und die eigentliche Funktion in der c file mit inline.
Dann klappt es auch auf dem raspi.

Was das ganze inline und extern bedeutet habe ich aber noch nicht raus, da
muss ich mich erst einlesen.

Ich teste das dann noch auf meinem banana und auch unter ubuntu.

--
Gruß Martin

Andreas W <notifications@github.com> schrieb am Fr., 20. Juli 2018, 11:33:

**Comment by hcanIngo** [comment]
Hallo Martin,
das klingt doch gut. Mal schauen, ob der alte Compiler damit auch zufrieden ist...

**inline:** Der Pre-Compiler versucht -falls möglich- den Code überall direkt ohne Funktionsaufruf einzusetzen. Führt zur Performance-Steigerung. Andererseits versucht der Pre-Compiler auch ohne inline bereits derartige Optimierungen.

**extern:** Die Funktion ist außerhalb dieser Datei aufrufbar.

@AndreasW79: Eine Anleitung für Raspberry ist eine schöne Erweiterung das Projekt. 

Viele Grüße,
Ingo

**Comment by hcanIngo** [comment]
Hey Martin,
sehr gut, dann ist es wohl damit geschafft. 
Sorry, ich bin erst einmal raus: Habe dem Ubuntu-Update von Version 17.10 auf 18.04 zugestimmt. Nun bootet der PC nicht mehr :(

Viele Grüße,
Ingo

**Comment by RealMerlin** [comment]
Hallo Ingo,
oh oh, ich hoffe du bekommst den Rechner schnell wieder zum laufen ..

Zum Thema. Ja die Änderungen waren definitiv nötig. Weil bei der aktuellen
Ubuntu LTS Version (18.04) ist das auch aufgetreten.
Ich hab das alles korrigiert. Die Inline und extern Geschichte.
Sowie die "ignoring return value" Warnings. Die hatte ich in meinem Fork
schon vor längerem korrigiert und das hat soweit gepasst.


--
Gruß Martin


2018-07-23 22:00 GMT+02:00 Ingo Lages <notifications@github.com>:

**Comment by hcanIngo** [comment]
ok, prima Martin!
Bin nun auch auf Ubuntu 18.04. Somit kann ich 17.04 nicht mehr prüfen. Habe daher 
https://github.com/hcanIngo/openHCAN/wiki/entwicklungsumgebung_installieren aktualisiert.

Viele Grüße,
Ingo
