### ISSUE TITLE
Host Interface Fehler

### ISSUE THREAD

**Issue by AndreasW79** [hcanIngo/openHCAN#18]
Guten Morgen,

ich habe aktuell ziemlich viele Fehler im hcanhid bis hin zu einem Fehler der den hcanhid dann auch beendet:

`hcanhid[22835]: Size mismatch: announced: 48, got: 3
hcanhid[22835]: resetting HI...
hcanhid[22835]: Size mismatch: announced: 48, got: 3
hcanhid[22835]: resetting HI...
hcanhid[22835]: Size mismatch: announced: 48, got: 3
hcanhid[22835]: resetting HI...
hcanhid[22835]: Size mismatch: announced: 48, got: 3
hcanhid[22835]: resetting HI...
hcanhid[22835]: Size mismatch: announced: 48, got: 3
hcanhid[22835]: resetting HI...
hcanhid[22835]: Size mismatch: announced: 48, got: 3
hcanhid[22835]: resetting HI...
hcanhid[22835]: Size mismatch: announced: 48, got: 3
hcanhid[22835]: resetting HI...
hcanhid[22835]: Size mismatch: announced: 48, got: 3
hcanhid[22835]: resetting HI...
hcanhid: unix_uart.c:69: recchar: Assertion `nread == 1' failed.
`

Bisher lief es seit gut 4 Jahren (ohne Neustart - ich war selbst überrascht) ohne einen Fehler.
Kompiliert wurde es damals auf dem rPI (3.18.7-v7+ #758 SMP PREEMPT Mon Feb 23 19:52:56 GMT 2015 armv7l GNU/Linux)

Nun wollte ich eine aktuelle Version kompilieren aber in den Sourcen befindet sich gar kein hcanhid mehr? Zuletzt in Release v2.
Habe ich etwas übersehen oder wird das klassische hostinterface gar nicht mehr weiter unterstützt und v2 ist die letzte Version des hcanhid?

Hat sonst jemand einen Vorschlag, eine Idee wie dieser Fehler entstehen kann?
Das USB Kabel habe ich bereits getauscht, alle Lötpunkte nachgelötet und in der Gesamtinstallation gab es auch keine
Änderungen, nicht einmal an den Konfigurationen der einzelnen Controller. Ich verwende ausschließlich normale C1612 v04, keine Bedienpanel oder Erweiterungen.

Vielen Dank vorab für Eure Unterstützung!
Andreas

**Comment by hcanIngo** [comment]
Hallo Andreas,
die Hostinterface-Hardware ist durch den Bananapi abgelöst..

Am 25.06.21 um 09:52 schrieb Andreas W:

**Comment by AndreasW79** [comment]
Hallo Ingo,

das habe ich fast befürchtet. In diesem Zuge und aus Verzweiflung habe ich dann noch einmal die Hardware die ich hatte
getestet und nachdem ich dann auch noch den passenden GND an dem Canberry Board (heute heißt es nur noch CAN BUS Dual [ISO] V2.1 Shield for Raspberry) angeschlossen hatte, funktioniert nun auch die Standard rPI Variante sehr gut. Ggf. schreibe ich noch einen Artikel über diese BananaPI Alternative.
Vorteil hierbei ist, dass es Out of the Box ohne Kernelanpassungen funktioniert, ggf. ist das auch heute bei dem BananaPI so. Und es passt als Shield auf alle gängigen rPIs. Und es ist Open Source Hardware, Eagle Files gibt es dort auf der Seite. (https://www.sg-electronic-systems.com/can-bus-dual-iso-v2-1-shield-for-raspberry/ oder ohne Isolation https://www.sg-electronic-systems.com/can-bus-dual-v2-1-shield-for-raspberry/) 

Viele Grüße

**Comment by RealMerlin** [comment]
Hallo Andreas,
unter Armbian wird im allgemeinen keine Kernelanpassung benötigt. Unter Bananian musste man das noch machen.
Allerdings hatte ich zuletzt die CAN Kommunikation unter den neueren Armbian Versionen nicht zum laufe bekommen.
Aktuell läuft es bei mir unter dieser Version:
ARMBIAN 5.85 stable Ubuntu 18.04.5 LTS 4.19.38-sunxi

Ein Artikel über eine BananaPI Alternative fände ich gut. Dann wäre man nicht so abhängig von der einen Hardware.


Viele Grüße,
Martin
