### ISSUE TITLE
images

### ISSUE THREAD

**Issue by hcanIngo** [hcanIngo/openHCAN#3]
![hcan-frame](https://cloud.githubusercontent.com/assets/4243148/11915338/5d925940-a6a2-11e5-8bc2-72a960732c72.png)
[1wire-pullups](https://cloud.githubusercontent.com/assets/4243148/11914655/be9e378e-a686-11e5-8c13-e6e034d67b68.jpg)
![anschlussplan-ds18b20](https://cloud.githubusercontent.com/assets/4243148/11915518/0c1c41b8-a6aa-11e5-96ef-00e1e091ce1a.png)

![hcan-ueberspannungsschutz](https://cloud.githubusercontent.com/assets/4243148/11915052/0de4a8aa-a696-11e5-9b9e-407a89986739.png)
![hcan-ueschutz-modul](https://cloud.githubusercontent.com/assets/4243148/11915051/0de4a2ec-a696-11e5-88c2-a43e0d8c36ed.jpg)
![rl_board bottom](https://cloud.githubusercontent.com/assets/4243148/11915053/0de9225e-a696-11e5-870e-b57f564a443f.jpg)
![rl_board top](https://cloud.githubusercontent.com/assets/4243148/11915054/0dec52c6-a696-11e5-91d7-6e401a2cd5af.jpg)
![rl_v58_b_bot](https://cloud.githubusercontent.com/assets/4243148/11915055/0ded5f36-a696-11e5-8ba4-b43d448baec9.png)
![rl_v58_b_top](https://cloud.githubusercontent.com/assets/4243148/11915056/0dee20d8-a696-11e5-8ced-65eec37d59c3.png)
![rl_v58_sch](https://cloud.githubusercontent.com/assets/4243148/11915057/0e00b464-a696-11e5-9a0f-bd444a3b304d.png)
![ueschutz-aufbau1](https://cloud.githubusercontent.com/assets/4243148/11915058/0e0158e2-a696-11e5-9f4d-a12198412191.jpg)
![ueschutz-funke](https://cloud.githubusercontent.com/assets/4243148/11915060/0e04fe48-a696-11e5-873c-ba2e3590dce8.jpg)
![ueschutz-ueberschwingen1](https://cloud.githubusercontent.com/assets/4243148/11915059/0e04d56c-a696-11e5-99d3-b1e62079e920.jpg)
![ueschutz-ueberschwingen2](https://cloud.githubusercontent.com/assets/4243148/11915061/0e0b63f0-a696-11e5-8789-ac7f21865578.jpg)
![patch bsp_c1612_mit_io_erweitung_von_32ausgaengen_und_56eingaengen](https://cloud.githubusercontent.com/assets/4243148/11915884/f24c8e86-a6b9-11e5-85d4-c1a16635ab0a.jpg)
![patch dcf77-anschluesse](https://cloud.githubusercontent.com/assets/4243148/11915885/f2660564-a6b9-11e5-994a-10a5c694bbad.jpg)

5d1bbad63e.png)
[app_1.1b.zip](https://github.com/hcanIngo/openHCAN/files/67559/app_1.1b.zip)
![aussentemp](https://cloud.githubusercontent.com/assets/4243148/11914662/d5a61352-a686-11e5-9b84-87827b1a824a.png)
![aussentemp-januar](https://cloud.githubusercontent.com/assets/4243148/11914663/d5b5001a-a686-11e5-8dc9-023316feba40.png)
![bedienfeld-1](https://cloud.githubusercontent.com/assets/4243148/11914665/d5b9e85a-a686-11e5-8431-53ada3879471.jpg)
![bedienfeld-2](https://cloud.githubusercontent.com/assets/4243148/11914666/d5baffec-a686-11e5-9c33-76eae17d5d8
![logo_open](https://cloud.githubusercontent.com/assets/4243148/11915822/1885c376-a6b8-11e5-8410-8ad30d1e1734.png)
c.jpg)
![bedienfeld-3](https://cloud.githubusercontent.com/assets/4243148/11914664/d5b9a160-a686-11e5-96d9-9a8ae38ed7f5.jpg)
![bpi_interfaces](https://cloud.githubusercontent.com/assets/4243148/11914667/d5bc9f96-a686-11e5-919a-b9a7d6731113.jpg)
![c1612-back](https://cloud.githubusercontent.com/assets/4243148/11914668/d5c140b4-a686-11e5-8aca-c8dc99cf45a7.jpeg)
![c1612-front](https://cloud.githubusercontent.com/assets/4243148/11914669/d5d11ee4-a686-11e5-8403-b87802dbb3c1.jpeg)
[c1612server_atmega466.hex.zip](https://github.com/hcanIngo/openHCAN/files/67560/c1612server_atmega466.hex.zip)
![controller1612-1](https://cloud.githubusercontent.com/assets/4243148/11914670/d5d5d74a-a686-11e5-839b-28596430adf8.jpg)
![controller-1612-2](https://cloud.githubusercontent.com/assets/4243148/11914671/d5da1eea-a686-11e5-97f8-0f63e57526bd.jpg)
![controller-1612-3](https://cloud.githubusercontent.com/assets/4243148/11914672/d5dec7c4-a686-11e5-8d05-16a96856ea39.jpg)
![controller-1612-4](https://cloud.githubusercontent.com/assets/4243148/11914673/d5def3a2-a686-11e5-842a-41ca35096a73.jpg)
![dcf77_pulsabtastung](https://cloud.githubusercontent.com/assets/4243148/11914674/d5f12194-a686-11e5-905c-0c79875cf554.jpg)
![dcf77_second60](https://cloud.githubusercontent.com/assets/4243148/11914675/d5f764e6-a686-11e5-8d87-92cf33978512.jpg)
![dcf77_second64](https://cloud.githubusercontent.com/assets/4243148/11914676/d5f9a5a8-a686-11e5-96a4-e62264e8f564.jpg)
![eds-layout](https://cloud.githubusercontent.com/assets/4243148/11914677/d5fd7520-a686-11e5-8799-69202865c648.png)
![hcan-hi-v02-anschluesse](https://cloud.githubusercontent.com/assets/4243148/11914678/d601d584-a686-11e5-9824-a403b3105dfb.png)
![hcan-protokoll-stack](https://cloud.githubusercontent.com/assets/4243148/11914679/d602d9ac-a686-11e5-8e6d-55076c18caec.png)
![hcan_rts_step1_lores](https://cloud.githubusercontent.com/assets/4243148/11914680/d612b322-a686-11e5-85e4-9db06c40ea09.jpg)
![hcan_rts_step2_lores](https://cloud.githubusercontent.com/assets/4243148/11914681/d61a258a-a686-11e5-8b30-59c0c0c990d1.jpg)
![hcan_rts_step3_lores](https://cloud.githubusercontent.com/assets/4243148/11914682/d61a7b84-a686-11e5-8441-591f3199f264.jpg)
[hcanweb-1.1b.apk.zip](https://github.com/hcanIngo/openHCAN/files/67561/hcanweb-1.1b.apk.zip)
![hcanweb_c1216server_spannungsversorgungsundspileitung](https://cloud.githubusercontent.com/assets/4243148/11914683/d620a82e-a686-11e5-92d8-66a5f12eeeec.jpg)
![hcanweb_c1216server_verdrahtung](https://cloud.githubusercontent.com/assets/4243148/11914684/d62a1df0-a686-11e5-9977-8fda4c0291a1.jpg)
![hostinterface-v02](https://cloud.githubusercontent.com/assets/4243148/11914685/d6633bee-a686-11e5-8ee3-754be2581493.jpg)
![in-erweiterung_64eingaenge](https://cloud.githubusercontent.com/assets/4243148/11914686/d667709c-a686-11e5-9ab1-53657a607243.jpg)
[io-expander32_eeprom_final_int.pdf](https://github.com/hcanIngo/openHCAN/files/67562/io-expander32_eeprom_final_int.pdf)
[io-expander64-4-osv.pdf](https://github.com/hcanIngo/openHCAN/files/67563/io-expander64-4-osv.pdf)
![modul_rts3](https://cloud.githubusercontent.com/assets/4243148/11914687/d66a3962-a686-11e5-9ccd-48e4c1edcee3.jpg)
![pin_def_gpio](https://cloud.githubusercontent.com/assets/4243148/11914688/d66a5744-a686-11e5-975d-4e5486899bf6.jpg)
![qr-code-hcanweb](https://cloud.githubusercontent.com/assets/4243148/11914689/d67fbe86-a686-11e5-9f5a-8327b010147d.png)
![screenshot_hcanweb_einstellungen](https://cloud.githubusercontent.com/assets/4243148/11914690/d68484ac-a686-11e5-8c64-b05c12ef278a.png)
![screenshot_hcanweb_fenster](https://cloud.githubusercontent.com/assets/4243148/11914691/d68d578a-a686-11e5-8223-d38a862c4ea5.png)
![screenshot_hcanweb_heizungen](https://cloud.githubusercontent.com/assets/4243148/11914692/d68f306e-a686-11e5-8794-31704bf0772b.png)
![screenshot_hcanweb_licht1](https://cloud.githubusercontent.com/assets/4243148/11914693/d692f6ae-a686-11e5-9fec-09bf1bd6c5df.png)
![screenshot_hcanweb_licht2](https://cloud.githubusercontent.com/assets/4243148/11914694/d6943df2-a686-11e5-88b4-afdd32c7ac25.png)
![screenshot_hcanweb_rollladen](https://cloud.githubusercontent.com/assets/4243148/11914695/d69e85f0-a686-11e5-8efd-037ff9f6ebec.png)
![screenshot_hcanweb_sonstige](https://cloud.githubusercontent.com/assets/4243148/11914696/d6a735ce-a686-11e5-8055-2d580f33b720.png)
![sfp](https://cloud.githubusercontent.com/assets/4243148/11914697/d6d8f514-a686-11e5-9a70-e3c2eb32478f.png)
![ueberblick1](https://cloud.githubusercontent.com/assets/4243148/11914698/d6dfaeea-a686-11e5-96ae-a4e5761fe9fe.jpg)
![ueberblick2](https://cloud.githubusercontent.com/assets/4243148/11914699/d6e15fec-a686-11e5-852c-acfdb45899ef.jpg)
![uispkabel](https://cloud.githubusercontent.com/assets/4243148/11914700/d6e23cbe-a686-11e5-9d4a-5ef8ca45b3c2.gif)

![logo](https://cloud.githubusercontent.com/assets/4243148/11906546/aa26f62e-a5cd-11e5-9f51-9ae772fecefe.jpg)

**Comment by RealMerlin** [comment]
![grafik](https://user-images.githubusercontent.com/24392133/51067308-4470a980-1611-11e9-9729-917f89844dc1.png)
![grafik](https://user-images.githubusercontent.com/24392133/51067397-2eafb400-1612-11e9-8aa7-1ba9e68fd174.png)
