### ISSUE TITLE
ROLLADEN_POSITION_SET - STOP Befehl möglich?

### ISSUE THREAD

**Issue by AndreasW79** [hcanIngo/openHCAN#6]
Hallo zusammen,

ist in der Erweiterung des Roll(l)aden-Devices ein Stop nun möglich?
Wie wäre derzeit ohne diese Erweiterung ein Stop möglich? Lediglich über einen Broadcast Meldung? Oder ein POWER_OFF an den Powerport (bringt das Laufzeit durcheinander?)
Wäre mit der neuen Firmware auf dem Controller und den neu Compilierten Tools ein ROLLADEN_POSITION_SET 202 dann dementsprechend ein STOP der Bewegung, also das 'Abschalten' des jeweiligen Power Ports möglich?

Grüße und Danke!
_Andreas

**Comment by hcanIngo** [comment]
Hallo Andreas,
per ROLLADEN_POSITION_SET 202 ist ein Stoppen des Rollladen vorgesehen. 

Im OpenHAB-Interface unter "Zusammenfassung der Rollläden" wird die 202 bei Betätigung des 'X' versendet und der Rollladen gestoppt.  

Im hcanweb-Interface ist das anfahren einer prozentualen Position per Schieberegler realisiert.

Viele Grüße von Ingo

**Comment by AndreasW79** [comment]
Hallo Ingo,

danke für die Info - dann werde ich das mal auf dem Rollladen Controller testen. Mir hat diese Funktion bisher in dieser Form gefehlt. Ich hatte in der Vergangenheit eine eigene kleine Oberfläche für die Devices erstellt und dort für Rollläden verschiedene Positionen festgelegt (0, 35, 50, 75. 100 - Prozent) wenn der Rollladen dann einmal rollt konnte man ihn aber nicht mehr aufhalten, besonders schlecht wenn man eine Gruppe von Rollläden steuert aber einen davon dann doch nicht bewegen will :) Oder habe ich die ganze Zeit eine Option hierfür übersehen?

Beste Grüße,
_Andreas

**Comment by hcanIngo** [comment]
Hallo Andreas,
dann kann der Vorgang ja geschlossen werden.

Viel Erfolg und Grüße,
Ingo
